#pragma once
void punchedcards(void);
void threedprinting(void);
void d1000000(void);
void chainreactions(void);
void twistylittlepassages(void);
void doubleoronething(void);
void equalsum(void);
void weightlifting(void);